form_assignment/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_details.urls', namespace='user_details'))
]

user_details/urls.py
from django.urls import path
from . import views


app_name = 'user_details'

urlpatterns = [
    path('', views.CreateProfileView.as_view(), name='create_profile'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name='user_profile')
]

user_details/models.py
from django.db import models
from django.core.validators import RegexValidator


TITLE_CHOICES = (
    ('Mr', 'Mr'),
    ('Mrs', 'Mrs'),
    ('Ms', 'Ms')
)


class UserDetails(models.Model):

    title = models.CharField(max_length=3, choices=TITLE_CHOICES, blank=True)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\d{10}$', message="Phone number must be entered in the format: '0123456789'. Up to 10 digits allowed.")
    contact = models.CharField(validators=[phone_regex], max_length=11, blank=True)
    address = models.TextField()

user_details/forms.py
from django import forms
from .models import UserDetails


class UserProfileForm(forms.ModelForm):

    class Meta:
        fields = ['title', 'name', 'email', 'password', 'contact', 'address']
        model = UserDetails
        widgets = {
            'password': forms.PasswordInput()
        }

user_details/views.py
from django.shortcuts import render
from django.views.generic import View
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import UserProfileForm
from .models import UserDetails


class CreateProfileView(View):

    template_name = 'user_details/create_profile.html'

    def get_context_data(self, *args, **kwargs):

        ctx = {}
        ctx['user_profile_form'] = UserProfileForm()
        return ctx

    def get(self, *args, **kwargs):

        ctx = self.get_context_data(*args, **kwargs)
        return render(self.request, self.template_name, ctx)

    def get_success_url(self, user_id):
        print('*****')
        
        return reverse_lazy('user_details:user_profile',
                            kwargs={'user_id': user_id})

    def post(self, *args, **kwargs):

        user_profile_form = UserProfileForm(self.request.POST)

        if user_profile_form.is_valid():
            print('form_valid')
            return self.form_valid(user_profile_form)

        else:
            print('form_invalid')
            return self.form_invalid(user_profile_form)

    def form_valid(self, user_profile_form):

        user_profile_form.save()
        email = user_profile_form.cleaned_data['email']
        user_id = UserDetails.objects.get(email=email).pk

        return HttpResponseRedirect(self.get_success_url(user_id))

    def form_invalid(self, user_profile_form):

        ctx = {'user_profile_form': user_profile_form}
        return render(self.request, self.template_name, ctx)


class UserProfileView(View):

    template_name = 'user_details/user_profile.html'

    def get_context_data(self, *args, **kwargs):

        ctx = {}
        ctx['user_profile'] = UserDetails.objects.get(pk=kwargs['user_id'])
        return ctx

    def get(self, *args, **kwargs):

        ctx = self.get_context_data(*args, **kwargs)
        return render(self.request, self.template_name, ctx)

user_details/templates/user_details/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
      {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      {% endblock meta %}

      <title>{% block title %} {% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="/static/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">
        <!-- Morris chart -->
        <link rel="stylesheet" href="/static/bower_components/morris.js/morris.css">
        <!-- jvectormap -->
        <link rel="stylesheet" href="/static/bower_components/jvectormap/jquery-jvectormap.css">
        <!-- Date Picker -->
        <link rel="stylesheet" href="/static/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
        <!-- Daterange picker -->
        <link rel="stylesheet" href="/static/bower_components/bootstrap-daterangepicker/daterangepicker.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <!-- Custom Theme Style -->
        <link rel="stylesheet" href="/static/build/css/custom.css">
      {% endblock stylesheets %}

      {% block extra_stylesheets %}
      <!-- For extra stylesheets -->
      {% endblock extra_stylesheets %}
    {% endblock head %}
  </head>

  <body class="{% block body_class %}hold-transition skin-blue sidebar-mini{% endblock body_class %}">
    {% block body %}
      <div class="wrapper">

        {% block top_navigation %}
          {% include "user_details/top_navigation.html" %}
        {% endblock top_navigation %}

        {% block sidebar %}
          <!-- Left side column. contains the logo and sidebar -->
          <aside class="main-sidebar">
            {% include "user_details/sidebar.html" %}
          </aside>
        {% endblock sidebar %}

        {% block content %}
          <!-- content -->
        {% endblock content %}

        {% block footer %}
          <footer class="main-footer">
            {% include "user_details/footer.html" %}
          </footer>
        {% endblock footer %}
      </div>

      {% block javascripts %}
        <!-- jQuery 3 -->
        <script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="/static/bower_components/jquery-ui/jquery-ui.min.js"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- InputMask -->
        <script src="/static/plugins/input-mask/jquery.inputmask.js"></script>
        <script src="/static/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
        <script src="/static/plugins/input-mask/jquery.inputmask.extensions.js"></script>
        <!-- Morris.js charts -->
        <script src="/static/bower_components/raphael/raphael.min.js"></script>
        <script src="/static/bower_components/morris.js/morris.min.js"></script>
        <!-- Sparkline -->
        <script src="/static/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
        <!-- jvectormap -->
        <script src="/static/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="/static/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <!-- jQuery Knob Chart -->
        <script src="/static/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
        <!-- daterangepicker -->
        <script src="/static/bower_components/moment/min/moment.min.js"></script>
        <script src="/static/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- datepicker -->
        <script src="/static/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
        <!-- Slimscroll -->
        <script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <!-- FastClick -->
        <script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
        <!-- AdminLTE App -->
        <script src="/static/dist/js/adminlte.min.js"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="/static/dist/js/pages/dashboard.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="/static/dist/js/demo.js"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script type="text/javascript">
          $.widget.bridge('uibutton', $.ui.button);
        </script>
      {% endblock javascripts %}

      {% block extra_javascripts %}
        <!-- For extra javascripts -->
      {% endblock extra_javascripts %}
    {% endblock body %}
  </body>
</html>

user_details/templates/user_details/create_profile.html
{% extends "user_details/base.html" %}
{% load widget_tweaks %}

{% block title %} Add User {% endblock title %}

{% block extra_stylesheets %}
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
  <!-- Select2 -->
  <link rel="stylesheet" href="/static/bower_components/select2/dist/css/select2.min.css">
{% endblock extra_stylesheets %}

{% block content %}
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Add User
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Add User</li>
      </ol>
    </section>

    <section class="content">

      <form role="form" method="POST" action="">
        {% csrf_token %}
        <div class="box box-default">
          <div class="box-header with-border">
            <h3 class="box-title">Personal Info</h3>
            <div class="box-tools pull-right">
              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
          </div>

          {% if user_profile_form.errors %}
            {% for error in user_profile_form.non_field_errors %}
              <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}

            {% for error in user_profile_form.errors %}
              <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}

          <div class="box-body">
            <div class="row">
              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label class="control-label">{{ user_profile_form.name.label }}</label>
                  {{ user_profile_form.name|add_error_class:"error-block" }}
                  <div class="error-text">
                    {% for error in user_profile_form.first_name.errors %}
                      {{ error|escape }}
                    {% endfor %}
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label class="control-label">{{ user_profile_form.email.label }}</label>
                  {{ user_profile_form.email|add_error_class:"error-block" }}
                  <div class="error-text">
                    {% for error in user_profile_form.email.errors %}
                      {{ error|escape }}
                    {% endfor %}
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label class="control-label">{{ user_profile_form.title.label }}</label>
                  {{ user_profile_form.title|add_error_class:"error-block" }}
                  <div class="error-text">
                    {% for error in user_profile_form.title.errors %}
                      {{ error|escape }}
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label class="control-label">{{ user_profile_form.password.label }}</label>
                  {{ user_profile_form.password|add_error_class:"error-block" }}
                  <div class="error-text">
                    {% for error in user_profile_form.password.errors %}
                      {{ error|escape }}
                    {% endfor %}
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label class="control-label">{{ user_profile_form.contact.label }}</label>
                  {{ user_profile_form.contact|add_error_class:"error-block" }}
                  <div class="error-text">
                    {% for error in user_profile_form.contact.errors %}
                      {{ error|escape }}
                    {% endfor %}
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label class="control-label">{{ user_profile_form.address.label }}</label>
                  {{ user_profile_form.address|add_class:"text-area-height"|add_error_class:"error-block" }}
                  <div class="error-text">
                    {% for error in user_profile_form.address.errors %}
                      {{ error|escape }}
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Submit Details</h3>
              </div>
              <div class="box-body">
                <div class="col-xs-6 col-md-2 col-lg-1 padding-left-null">
                  <button type="submit" class="btn btn-block btn-success">Submit</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </section>
  </div>
{% endblock content %}

{% block extra_javascripts %}
  <!-- Bootstrap WYSIHTML5 -->
  <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
  <!-- Select2 -->
  <script src="/static/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- Page script -->
  <script type="text/javascript">
    // To activate the relevant sidebar element
    $("#sidebar-users").addClass("active");

    //Initialize Select2 Elements
    $('.select2').select2({
      'closeOnSelect': false
    });
  </script>
{% endblock extra_javascripts %}

user_details/templates/user_details/footer.html
<strong>Copyright &copy; <a href="">Dixit Group </a>.</strong> All rights reserved.

user_details/templates/user_details/sidebar.html
<section class="sidebar">
  <div class="user-panel">
    <div class="pull-left image">
      <img src="/static/dist/img/anonymous-user.png" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
      <p>Aman Dixit</p>
      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>
  <ul class="sidebar-menu" data-widget="tree">
    <li class="header">MAIN NAVIGATION</li>
    <li id="sidebar-users">
      <a href="{% url 'user_details:create_profile' %}">
        <i class="fa fa-users"></i> <span>Add User</span>
      </a>
    </li>
  </ul>
</section>

user_details/templates/user_details/top_navigation.html
<header class="main-header">
  <!-- Logo -->
  <a href="#" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>D</b>G</span>
      <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Dixit</b> Group</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-user" style="font-size: 17px;"></span>
            <span class="hidden-xs">Aman Dixit</span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <span class="glyphicon glyphicon-user" style="font-size: 50px;"></span>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

user_details/templates/user_details/user_profile.html
{% extends "user_details/base.html" %}
{% load widget_tweaks %}

{% block title %} User Profile {% endblock title %}

{% block extra_stylesheets %}
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
{% endblock extra_stylesheets %}

{% block content %}
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        User Profile
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'user_details:create_profile' %}"><i class="fa fa-dashboard"></i> User</a></li>
        <li class="active">User profile</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-3">
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="/static/dist/img/anonymous-user.png" alt="User profile picture">
              <h3 class="profile-username text-center">{{ user_profile.name|default_if_none:'' }}</h3>
            </div>
          </div>

        </div>
        <div class="col-xs-9">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#personal-info" data-toggle="tab">Personal Info</a></li>
              <li class="pull-right margin-right-9">
                <a href="" class="no-padding">
                  <button class="btn btn-success">Edit</button>
                </a>
              </li>
            </ul>

            <div class="tab-content">
              <div class="active tab-pane" id="personal-info">
                <form class="form-horizontal">
                  <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputName" placeholder="Name" disabled="true" value="{{ user_profile.name|default_if_none:'' }}">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" id="inputEmail" placeholder="Email" disabled="true" value="{{ user_profile.email|default_if_none:'' }}">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputCellPhone" class="col-sm-2 control-label">Contact</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputCellPhone" placeholder="Mobile" disabled="true" value="{{ user_profile.contact|default_if_none:'' }}">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputStreet" class="col-sm-2 control-label">Address</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputStreet" placeholder="Address" disabled="true" value="{{ user_profile.address|default_if_none:'' }}">
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

{% block extra_javascripts %}
  <!-- Bootstrap WYSIHTML5 -->
  <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
  <!-- Page script -->
  <script type="text/javascript">
    // To activate the relevant sidebar element
    $("#sidebar-users").addClass("active");

    // To remove the toolbar's li element of editor
    $(document).ready(function() {
      $(".wysihtml5-toolbar").remove();
    });
  </script>
{% endblock extra_javascripts %}